# Generated by Django 2.1.1 on 2018-12-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_resume_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('university', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('principles_foundations', models.BooleanField()),
                ('technology_enablers', models.BooleanField()),
            ],
        ),
    ]
