# Generated by Django 2.1.1 on 2018-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='principles_foundations',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='technology_enablers',
            field=models.BooleanField(blank=True),
        ),
    ]
