# Generated by Django 2.1.1 on 2018-12-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181215_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(choices=[('toronto', 'University of Toronto'), ('waterloo', 'University of Waterloo'), ('ets', 'ETS'), ('laval', 'Laval University')], max_length=150),
        ),
    ]
