# Generated by Django 2.1.1 on 2018-12-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20181215_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('MEng', 'MEng.'), ('MASc', 'MASc.'), ('Phd', 'Phd.')], max_length=150),
        ),
    ]
